### PR TITLE
ducktape: Save command line on start and add it to HTML report

### PR DESCRIPTION
**Pull request by savex**
With minimal changes to structure and test flow, added command line as it was in `sys.argv`

### CODE REVIEW

**Comment by savex** [comment]
Python py38 check failed because it runs without proper privileges while trying to build zmq

**Comment by ivotron** [comment]
i wonder when/how this started to fail. we should create a ticket to fix. Maybe synchronizing with upstream would take care of it (?)

**Comment by savex** [comment]
Rebased to master, fixed one flake8 error and bumped pyyaml version to 6.0.1 according to this [issue](https://github.com/yaml/pyyaml/issues/601)

**Review by andrewhsu — CHANGES_REQUESTED** [review]
this needs a rebase with the tip of `master`. looks like ff42f76 is a merge commit. rebase will have the git commits stacked on top of `master` which will help reason about the differences with upstream.

other than that, changes lgtm.

**Comment by savex** [comment]
I personally do not know what to do next. I am lost in the branches and where should what go :)

**Comment by andrewhsu** [comment]
> I personally do not know what to do next. I am lost in the branches and where should what go :)

i just tried to rebase against [master](https://github.com/redpanda-data/ducktape/tree/master) with
```
git rebase master
```
and it looks like git has conflict with each one of the 48 commits in this PR which i feel is unnecessary to resolve because it is pretty much just doing what was done in https://github.com/redpanda-data/devprod/issues/332 all over again.

i think it would be easier to open a new PR to `master` (make sure you start from latest of tip of `master`) and just create a new commit with the changes shown in https://github.com/redpanda-data/ducktape/pull/27/files which are only `+10 -1` lines.

**Review by andrewhsu — CHANGES_REQUESTED** [review]
the git history for this PR is looking much better now, just 4 commits but i believe  8a6567d24f572bd50717f6c9224a4f57df1aede5 and 4b48071140356dbe2b129afa39bca36ded9b6e92 are not needed in this PR because the changes already exist in the tree. you can drop these commits with:
```
git rebase -i
```

**Review by andrewhsu — APPROVED** [review]
LGTM

after this merges, be sure to update https://github.com/redpanda-data/redpanda/blob/dev/tests/setup.py with the new git commit from `master` branch

**Comment by andrewhsu** [comment]
> after this merges, be sure to update https://github.com/redpanda-data/redpanda/blob/dev/tests/setup.py with the new git commit from master branch

or update https://github.com/redpanda-data/redpanda/pull/13116

**Pull request merged**
