### PR TITLE
mark: add kwargs to ok_to_fail

### PR DESCRIPTION
**Pull request by NyaliaLui**
Currently `ok_to_fail` does not take param arguments and the decorator can only be used for a whole test function. The consequence of this is that tests with a `@matrix` of several params cannot mark individual permutations as `ok_to_fail`.

This PR adds args to the `ok_to_fail` decorator.

### CODE REVIEW

**Comment by NyaliaLui** [comment]
My py-linter auto ran and modified the format to several .py files. Hopefully that doesn't break CI

**Comment by NyaliaLui** [comment]
Closing since `ignore` is still reported in CI.

**Comment by jcsp** [comment]
Can you undo the extra format changes?  Given that ducktape is something we may well rebase on upstream in future, it'll be painful at that point.

**Comment by NyaliaLui** [comment]
Closing since I don't think there is a strong need for this.

**Pull request closed without merging**
